version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "free"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
