# Port to run the ServerSelectorX API on.
# ServerSelectorX-Connector connects to this port to send server information.
# https://github.com/ServerSelectorX/ServerSelectorX/wiki/Installing-SSX-Connector
port: 9782





# -------------------- Advanced -------------------- #

# https://github.com/ServerSelectorX/ServerSelectorX/wiki/Premium-security
password: "a"

# The number of milliseconds without a ping until ServerSelectorX
# will consider a server as offline.
server-offline-timeout: 6000

# Normally, you can access files in the ServerSelectorX plugin folder through the
# SSX API. This is used by the config sync feature to get files from another
# server. By default, SSX prevents accessing other directories. By turning this
# off, SSX will allow accessing any file through the API. ANY file!! Your databases,
# passwords, any file readable by the user running the server. If you want
# to sync files from different plugins between servers you're probably better
# off using an external tool like rsync.
block-outside-directory: true

jetty-debug: false