# Port to run the ServerSelectorX API on.
# ServerSelectorX-Connector connects to this port to send server information.
# https://github.com/ServerSelectorX/ServerSelectorX/wiki/Installing-SSX-Connector
port: 9782





# -------------------- Advanced -------------------- #

# https://github.com/ServerSelectorX/ServerSelectorX/wiki/Premium-security
password: "a"

# The number of milliseconds without a ping until ServerSelectorX
# will consider a server as offline.
server-offline-timeout: 6000

# When set to false, you can sync files outside of the SSX data folder.
# This will expose all your server files (possibly even system files) through the API!
# Make sure the API is secured properly before disabling this.
block-outside-directory: true

jetty-debug: false