# For very advanced chat messages using the Spigot ChatComponent API.
# Add messages below, then use then using the action 'chatcomponent:<messagename>`
# Documentation here: https://github.com/Derkades/Derkutils/wiki/Chat-component-YAML

# THIS FEATURE IS NOW DEPRECATED
# it will removed in a future release
# use adventure messages instead

examplemessage:
  - text: 'This part is blue and bold. '
    bold: true
    color: BLUE
  - text: 'This part has a hover effect and a link.'
    hover: 'Click me!'
    url: 'https://example.com'
    underlined: true
  - text: 'Click me to run a command'
    run_command: 'say hi'