# List the effects and the desired amplifier here.
# Amplifier 0 shows up as I in game, so amplifier 1 is II
# https://github.com/ServerSelectorX/ServerSelectorX/wiki/Effects
effects:
  SPEED: 2
  JUMP: 0

# Effects to apply on join. They must be set above
join:
 - SPEED



# -------------------- Advanced -------------------- #

# When set to true, give an ambient effect (like beacons) instead of effects without particles.
# 1.8+ supports effects without particles.
# You have to set this to true for 1.7.10 servers.
show-particles: false