# Color codes are supported in all 'user-friendly name' fields.
# Please note that if you want to use color codes or special characters
# such as '!' you have to enclose your string into quotation marks.
# For example:
#
# name: '&aFancy &cColors!'

# The name of the server selector item.
item: COMPASS

# Give the item when a player joins?
on-join: true

# What slot should the item be in?
inv-slot: 0

# Number of rows of slots of your server selector menu. For example '2' will mean 2*9 = 18 slots. Max value is 6.
rows: 2

# This will be displayed as the title of the menu. (e.g. where it would usually say 'chest')
title: 'Server Selector'

# Require the permission 'ssx.use' to open the menu
permissions-enabled: false
# Send a message if the player does not have permission to use the server selector?
no-permission-message-enabled: true
no-permission-message: '&cYou do not have permission to use the server selector.'

# Latest sound names (currently for 1.12-pre5): https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
# 1.7.10 sound names: https://jd.bukkit.org/org/bukkit/Sound.html
# 1.8 sound names: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html

# Most 1.8 sound names should work on 1.9-1.11 too. Please use sound names corresponding to your server version.
# If you don't want any sound to play put 'NONE' without ''
selector-open-sound: HORSE_ARMOR

ping-error-message-selector: '&cServer is not reachable'

# How long a server needs to be pinged for before giving up. (in milliseconds)
# Set this to a higher value if your servers are very slow.
# Warning: Increasing this value increases lag
ping-timeout: 100

# Enable error messages to console if the server is not reachable. (true or false)
ping-error-message-console: true

# This is where all menu entries go.
# You only need to specify 'ip' and 'port' if 'show-player-count' is set to true.
menu:
  3:
    item: DIAMOND_SWORD
    data: 0
    server: kitpvp
    name: KitPvP Server
    lore:
      - Line 1
      - Line 2
    show-player-count: false
    player-count: 'There are {x} players online.' 
    ip: play.example.com
    port: 1234
  5:
    item: GRASS
    data: 0
    server: creative
    name: '&aBuild!!!'
    lore:
      - '&bLine &c1'
      - '&5Line 2'
      - Line 3
    show-player-count: false
    player-count: 'There are {x} out of {y} players online.' 
    ip: play.example.com
    port: 54321
    
# Do not touch this
version: 3