name: ServerSelectorX
main: xyz.derkades.serverselectorx.Main
version: 1.4.0
author: Derkades
description: 'The best server selector plugin ever!'
website: 'https://www.spigotmc.org/resources/serverselectorx.32853/'

commands:
  serverselectorx:
    aliases: [ss,ssx,serversel,serverselector]
    description: The one and only command of the ServerSelectorX plugin.
    usage: |-
      Aliases: serverselectorx, ss, ssx, serversel, serverselector
      
      /ssx reload/rl - reloads the config