# Show message when player teleports to a server.
# Remove/comment this option to disable the message
server-teleport-message: '&7Connecting you to &7&l{x}&r&7.'

# Cancel item dropping for players that do not have the permission ssx.drop
cancel-item-drop: false

# Cancel item move for players that do not have the permission ssx.move (this includes swapping items between hands for 1.9+)
cancel-item-move: false


# Set a ping API. If server pinging is giving errors, choose a different ping API.
# I recommend trying all internal pinging APIs before moving on to external ones,
# since those require you to port forward your spigot servers.
#
# minestat: internal pinger (https://github.com/FragLand/minestat)
# jamiete: internal pinger(https://github.com/jamietech/MinecraftServerPing)
# minetools: external pinger (api.minetools.eu)
ping-api: jamiete

ping-timeout: 500

ping-debug: false