# Show message when player teleports to a server.
# Remove/comment this option to disable the message
server-teleport-message: '&7Conecting you to &7&l{x}&r&7.'

# Cancel item dropping for players that do not have the permission ssx.drop
cancel-item-drop: false

# Cancel item move for players that do not have the permission ssx.move (this includes swapping items between hands for 1.9+)
cancel-item-move: false

# Cooldown for opening the selector menu in milliseconds.
# This can be used as workaround for a bug where players are able to take out items if they
# click the selector again while it is still waiting for servers to be pinged from the first time they clicked.
# This value is in milliseconds. Any value less than 1000 = cooldown off.
selector-open-cooldown: 2000

# Remove/comment this option to disable the message. Disabling the message
# does not disable the cooldown.
cooldown-message: '&cYou cannot use this yet, please wait {x} seconds.'

# -------------------- Server Pinging -------------------- #

# Use an external query API for pinging servers. This is recommended.
# The internal query has a lot of problems, one of which is that it doesn't
# work when there are color codes anywhere in the motd. Version support is 
# terrible as well. If you have your spigot servers behind a firewall (which 
# you should) allow the domain api.minetools.eu to ping your server.
external-query: true

# How long a server needs to be pinged for before giving up. (in milliseconds)
# Set this to a higher value if your servers are not responding in time.
# This setting has effect on the internal query only.
ping-timeout: 500


