# Show message when player teleports to a server.
# Remove/comment this option to disable the message
server-teleport-message: '&7Connecting you to &7&l{x}&r&7.'

# Cancel item dropping for players that do not have the permission ssx.drop
cancel-item-drop: false

# Cancel item move for players that do not have the permission ssx.move (this includes swapping items between hands for 1.9+)
cancel-item-move: false

# Cooldown for opening the selector menu in milliseconds.
# This can be used as workaround for a bug where players are able to take out items if they
# click the selector again while it is still waiting for servers to be pinged from the first time they clicked.
# This value is in milliseconds. Any value less than 1000 = cooldown off.
selector-open-cooldown: 2000

# Remove/comment this option to disable the message. Disabling the message
# does not disable the cooldown.
cooldown-message: '&cYou cannot use this yet, please wait {x} seconds.'


# -- Advanced options --

# Use an external query API for pinging servers (recommended)
# You can use the internal query system, but it can't handle
# colored motds and it may not support all versions.
external-query: true

# Internal query only
ping-timeout: 500