name: ServerSelectorX
main: xyz.derkades.serverselectorx.Main
version: '@project.version@'
author: Derkades
description: 'An up-to-date customizable server selector plugin.'
website: 'https://www.spigotmc.org/resources/serverselectorx-premium.63855/'
softdepend: [PlaceholderAPI]
api-version: 1.13

commands:
  serverselectorx:
    aliases: [ssx]
    description: The one and only command of the ServerSelectorX plugin.
    usage: |-      
      /ssx reload/rl - Reload configuration files
      /ssx reloadcommands/rlcmd - Reloads commands (sort of)
      /ssx status - Show SSX-Connector status
      /ssx items - List names of loaded items
      /ssx menus - List names of loaded menus
      /ssx commands - List names of loaded commands
      /ssx lagdebug - Enable lag debug mode
      /ssx itemdebug - Enable item debug mode
      /ssx sync - Force config sync (even if disabled)
      /ssx synclist - Get a list of files that would be synced by config sync