name: ServerSelectorX
main: xyz.derkades.serverselectorx.Main
version: '@project.version@'
author: Derkades
description: 'A modern server selector plugin with an advanced but simple config file.'
website: 'https://www.spigotmc.org/resources/serverselectorx.32853/'
softdepend: [PlaceholderAPI]
api-version: 1.13

commands:
  serverselectorx:
    aliases: [ssx]
    description: The one and only command of the ServerSelectorX plugin.
    usage: |-      
      /ssx reload/rl - Reload configuration files
      /ssx reloadcommands/rlcmd - Reloads commands (sort of)
      /ssx status - Show SSX-Connector status
      /ssx items - List names of loaded items
      /ssx menus - List names of loaded menus
      /ssx commands - List names of loaded commands
      /ssx lagdebug - Enable lag debug mode
      /ssx itemdebug - Enable item debug mode