name: ServerSelectorX
main: xyz.derkades.serverselectorx.Main
version: '@project.version@'
author: Derkades
description: 'A simple server selector plugin'
website: 'https://www.spigotmc.org/resources/serverselectorx.32853/'
softdepend: [PlaceholderAPI]
api-version: 1.13

commands:
  serverselectorx:
    aliases: [ssx]
    usage: |-
      Aliases: serverselectorx, ssx
      
      /ssx reload/rl - reloads the config