name: ServerSelectorX
main: xyz.derkades.serverselectorx.Main
version: '@project.version@'
author: Derkades
description: 'A modern server selector plugin with an advanced but simple config file.'
website: 'https://www.spigotmc.org/resources/serverselectorx.32853/'
softdepend: [PlaceholderAPI]
api-version: 1.13

commands:
  serverselectorx:
    aliases: [ss,ssx,serversel,serverselector]
    description: The one and only command of the ServerSelectorX plugin.
    usage: |-
      Aliases: serverselectorx, ss, ssx, serversel, serverselector
      
      /ssx reload/rl - reloads the config