# Please note that if you want to use color codes or special characters 
# you have to enclose your string into quotation marks, for example:
#
# name: '&aFancy &cColors!'



server-teleport-message-enabled: true
server-teleport-message: '&7You are being connected to &7&l{x}&r&7.'

# Clear chat before sending player to server? 
# Note: the chat will be cleared before sending server teleport message, so the server teleport message will still be visible.
chat-clear: false


# -------------------- Permissions -------------------- #

# Require the permission 'ssx.use.<selector name>' to open the menu and ssx.join.<selector name> to get the item on join
permissions-enabled: false

# Send a message if the player does not have permission to use the server selector?
no-permission-message-enabled: true
no-permission-message: '&cYou do not have permission to use the server selector.'


# -------------------- Sounds -------------------- #

# Latest sound names (currently for 1.12.2): https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
# 1.7.10 sound names: https://jd.bukkit.org/org/bukkit/Sound.html or http://docs.codelanx.com/Bukkit/1.7.10/org/bukkit/Sound.html
# 1.8 sound names: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html

# Please use sound names corresponding to your server version.
# If you don't want any sound to play put 'NONE' without ''

selector-open-sound: HORSE_ARMOR



# -------------------- Items -------------------- #

# Cancel item dropping for players that do not have the permission ssx.drop
cancel-item-drop: false

# Cancel item move for players that do not have the permission ssx.move (this includes swapping items between hands for 1.9+)
cancel-item-move: false


# Please only disable the updater if it is causing issues or you cannot use a newer version of the plugin.
# New versions will not be downloaded or installed automatically, it just checks if a new version is available.
# Keep in mind that you will get limited or no support for older versions.
updater: true

# Do not touch this
version: 8